### ISSUE TITLE
Query. What is the requirement to add middleware as a proc in controllers

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#29]
I have a controller that looks like the following.

```rb
class App < Scorched::Controller
  middleware << proc do
    use Rack::Session::Cookie, secret: 'blah'
    use Rack::Csrf, :raise => true
  end
end
```

I was looking into adding code to be able to do the following. 

```rb
class App < Scorched::Controller
    use Rack::Session::Cookie, secret: 'blah'
    use Rack::Csrf, :raise => true
end
```

However I was wondering if you had a reason to not do this before I tripped over a problem you had already thought about

**Comment by Wardrop** [comment]
Good question. It's a matter of flexibility and utility. When building Scorched, I made every effort to implement functionality using Scorched constructs, by which I mean writing as much functionality of Scorched using other Scorched functions or behaviour. You'll find quite a few examples in the source code where I use the filter and middleware constructs from Scorched to implement additional behaviours. The good thing about doing this is that you find limitations and design flaws before you even use the framework for a real application.

This is likely why I chose to implement middleware this way. Middleware loading needs to be implemented as a proc in order to do conditional loading of middleware, and to be able to use variables when configuring middleware.

A perfect example is included in `controller.rb` itself; hence the first paragraph: https://github.com/Wardrop/Scorched/blob/master/lib/scorched/controller.rb#L87-L94

```ruby
middleware << proc { |controller|
  use Rack::Head
  use Rack::MethodOverride
  use Rack::Accept
  use Scorched::Static, controller.config[:static_dir] if controller.config[:static_dir]
  use Rack::Logger, controller.config[:logger] if controller.config[:logger]
  use Rack::ShowExceptions if controller.config[:show_exceptions]
}
```

The base Scorched::Controller includes a bunch of middleware by default, but notice how half of the middleware will only load depending on the controller configuration. Because this is in a proc, we can delay execution and set `controller` to whatever controller actually handle the request, which may alter these configuration variables (or any of it's parents).

So declaring middleware in a proc allows the follow to work as expected:

```ruby
class MyApp < Scorched::Controller
  config[:show_exceptions] = true
end
```

Otherwise, `use Rack::ShowExceptions if controller.config[:show_exceptions]` would always be evaluated in the root `Scorched::Controller` where `config[:show_exceptions]` is false, and so this middleware would never load unless you altered `Scorched::Controller.config[:show_exceptions]`, which would be global and very naughty. I'd have to come to your house and spank you.

Hopefully that makes it pretty clear. Thanks for asking as it forced to re-work out why I did it like that. I certainly knew there was a reason as I wouldn't make something uglier than it needs to be for no reason ;)

**Comment by CrowdHailer** [comment]
Thanks. Thats a really helpful explination and quick. I did go through the source code a few weeks ago on a train journey but had not picked up on that. This is the first time i have delved quite so deep into the workings of rack and friends.

**Comment by Wardrop** [comment]
Yeah it's pretty subtle. The whole inheritability aspect of Scorched makes it powerful and simple to the user, but can make the source code a little harder to get your head around. You've got to be in the right head space :)
