### ISSUE TITLE
Redirect with flash message

### ISSUE THREAD

**Issue by CrowdHailer** [Wardrop/Scorched#36]
This is a feature request. I would have made it as a pull request but I am struggling to get the tests to work locally. Would it be possible to have the redirect handle and options hash as flash messages

In the [controller](https://github.com/Wardrop/Scorched/blob/master/lib/scorched/controller.rb#L373)

```rb
def redirect(url, status = (env['HTTP_VERSION'] == 'HTTP/1.1') ? 303 : 302)
  response['Location'] = absolute(url)
  halt(status)
end
```

To be upgraded to something like

```rb
def redirect(url, status = (env['HTTP_VERSION'] == 'HTTP/1.1') ? 303 : 302, **flashes)
  response['Location'] = absolute(url)
  flash.merge! flashes
  halt(status)
end
```

**Comment by Wardrop** [comment]
It'd be trivial to add. The question is whether it's worth adding. I'm hesitant to add something of a catch all (i.e. *var or **var) to the end of a method like this, mainly because it limits the range of low impact (i.e backwards-compatible) API changes available in the future. Feel free to monkey path your own implementation into projects.

``` ruby
def redirect(*args, **flashes)
  super *args
  flash.merge! flashes
end
```

I'll keep the suggestion in mind though. If someone else bumps this as a feature request, or I suppose if I find a need for it in my own projects, I'll add it.

**Comment by CrowdHailer** [comment]
Thanks for the monkey patch. For some reason had only seen the rewrite solution. I will probably start using that in every project. I would like to put my vote in that it does help take the final bit of compexity out of my command paths I try to take everything out of the controller layer so I have a number that look like this

```rb
post '/' do
  if action.success?
    flash['success'] = 'well done'
    redirect '/home'
  else
    flash['error'] = 'Uh oh'
    redirect '/other'
  end
end

To get two lines out of such a small controller action feels like a big win. But maybe I am focusing on the wrong thing and there maybe no place for it not returning HTML

**Comment by CrowdHailer** [comment]
With the money patch above I get the following error

>[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by Wardrop** [comment]
Hmm, what ruby version are you using? I did just notice that my monkey patch is the wrong way around. I also decided to test it this time as I had doubt's whether #merge! would work. Sure enough, it doesn't due to the nature of how flash is implemented and the requirement for method redirection. Anyway, try this...

```ruby
def redirect(*args, **flashes)
  flashes.each { |k,v| flash[k] = v }
  super *args
end
```

**Comment by CrowdHailer** [comment]
I am using ruby 2.2.0.

It's probably an interesting problem if i get the time to look at it.
